//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int WeatherID { get; set; }
        public int CityID { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public string WindDirection { get; set; }
        public string WindSpeed { get; set; }
        public string TypeOfWind { get; set; }
        public string CelciusTemperature { get; set; }
        public string TypeofWeather { get; set; }
    
        public virtual City City { get; set; }
    }
}
